# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kerneleditor.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(583, 279)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.threeSize = QtWidgets.QWidget()
        self.threeSize.setObjectName("threeSize")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.threeSize)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.widget = QtWidgets.QWidget(self.threeSize)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.widget)
        self.doubleSpinBox.setMinimum(-10.0)
        self.doubleSpinBox.setMaximum(10.0)
        self.doubleSpinBox.setSingleStep(0.05)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.verticalLayout.addWidget(self.doubleSpinBox)
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.widget)
        self.doubleSpinBox_3.setMinimum(-10.0)
        self.doubleSpinBox_3.setMaximum(10.0)
        self.doubleSpinBox_3.setSingleStep(0.05)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.verticalLayout.addWidget(self.doubleSpinBox_3)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.widget)
        self.doubleSpinBox_2.setMinimum(-10.0)
        self.doubleSpinBox_2.setMaximum(10.0)
        self.doubleSpinBox_2.setSingleStep(0.05)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.verticalLayout.addWidget(self.doubleSpinBox_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.widget)
        self.doubleSpinBox_4.setMinimum(-10.0)
        self.doubleSpinBox_4.setMaximum(10.0)
        self.doubleSpinBox_4.setSingleStep(0.05)
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.verticalLayout_2.addWidget(self.doubleSpinBox_4)
        self.doubleSpinBox_5 = QtWidgets.QDoubleSpinBox(self.widget)
        self.doubleSpinBox_5.setMinimum(-10.0)
        self.doubleSpinBox_5.setMaximum(10.0)
        self.doubleSpinBox_5.setSingleStep(0.05)
        self.doubleSpinBox_5.setObjectName("doubleSpinBox_5")
        self.verticalLayout_2.addWidget(self.doubleSpinBox_5)
        self.doubleSpinBox_6 = QtWidgets.QDoubleSpinBox(self.widget)
        self.doubleSpinBox_6.setMinimum(-10.0)
        self.doubleSpinBox_6.setMaximum(10.0)
        self.doubleSpinBox_6.setSingleStep(0.05)
        self.doubleSpinBox_6.setObjectName("doubleSpinBox_6")
        self.verticalLayout_2.addWidget(self.doubleSpinBox_6)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.doubleSpinBox_7 = QtWidgets.QDoubleSpinBox(self.widget)
        self.doubleSpinBox_7.setMinimum(-10.0)
        self.doubleSpinBox_7.setMaximum(10.0)
        self.doubleSpinBox_7.setSingleStep(0.05)
        self.doubleSpinBox_7.setObjectName("doubleSpinBox_7")
        self.verticalLayout_3.addWidget(self.doubleSpinBox_7)
        self.doubleSpinBox_8 = QtWidgets.QDoubleSpinBox(self.widget)
        self.doubleSpinBox_8.setMinimum(-10.0)
        self.doubleSpinBox_8.setMaximum(10.0)
        self.doubleSpinBox_8.setSingleStep(0.05)
        self.doubleSpinBox_8.setObjectName("doubleSpinBox_8")
        self.verticalLayout_3.addWidget(self.doubleSpinBox_8)
        self.doubleSpinBox_9 = QtWidgets.QDoubleSpinBox(self.widget)
        self.doubleSpinBox_9.setMinimum(-10.0)
        self.doubleSpinBox_9.setMaximum(10.0)
        self.doubleSpinBox_9.setSingleStep(0.05)
        self.doubleSpinBox_9.setObjectName("doubleSpinBox_9")
        self.verticalLayout_3.addWidget(self.doubleSpinBox_9)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.horizontalLayout_5.addWidget(self.widget)
        self.tabWidget.addTab(self.threeSize, "")
        self.fiveSize = QtWidgets.QWidget()
        self.fiveSize.setObjectName("fiveSize")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.fiveSize)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.doubleSpinBox_13 = QtWidgets.QDoubleSpinBox(self.fiveSize)
        self.doubleSpinBox_13.setMinimum(-10.0)
        self.doubleSpinBox_13.setMaximum(10.0)
        self.doubleSpinBox_13.setSingleStep(0.05)
        self.doubleSpinBox_13.setObjectName("doubleSpinBox_13")
        self.verticalLayout_5.addWidget(self.doubleSpinBox_13)
        self.doubleSpinBox_14 = QtWidgets.QDoubleSpinBox(self.fiveSize)
        self.doubleSpinBox_14.setMinimum(-10.0)
        self.doubleSpinBox_14.setMaximum(10.0)
        self.doubleSpinBox_14.setSingleStep(0.05)
        self.doubleSpinBox_14.setObjectName("doubleSpinBox_14")
        self.verticalLayout_5.addWidget(self.doubleSpinBox_14)
        self.doubleSpinBox_15 = QtWidgets.QDoubleSpinBox(self.fiveSize)
        self.doubleSpinBox_15.setMinimum(-10.0)
        self.doubleSpinBox_15.setMaximum(10.0)
        self.doubleSpinBox_15.setSingleStep(0.05)
        self.doubleSpinBox_15.setObjectName("doubleSpinBox_15")
        self.verticalLayout_5.addWidget(self.doubleSpinBox_15)
        self.doubleSpinBox_16 = QtWidgets.QDoubleSpinBox(self.fiveSize)
        self.doubleSpinBox_16.setMinimum(-10.0)
        self.doubleSpinBox_16.setMaximum(10.0)
        self.doubleSpinBox_16.setSingleStep(0.05)
        self.doubleSpinBox_16.setObjectName("doubleSpinBox_16")
        self.verticalLayout_5.addWidget(self.doubleSpinBox_16)
        self.doubleSpinBox_17 = QtWidgets.QDoubleSpinBox(self.fiveSize)
        self.doubleSpinBox_17.setMinimum(-10.0)
        self.doubleSpinBox_17.setMaximum(10.0)
        self.doubleSpinBox_17.setSingleStep(0.05)
        self.doubleSpinBox_17.setObjectName("doubleSpinBox_17")
        self.verticalLayout_5.addWidget(self.doubleSpinBox_17)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.doubleSpinBox_18 = QtWidgets.QDoubleSpinBox(self.fiveSize)
        self.doubleSpinBox_18.setMinimum(-10.0)
        self.doubleSpinBox_18.setMaximum(10.0)
        self.doubleSpinBox_18.setSingleStep(0.05)
        self.doubleSpinBox_18.setObjectName("doubleSpinBox_18")
        self.verticalLayout_6.addWidget(self.doubleSpinBox_18)
        self.doubleSpinBox_19 = QtWidgets.QDoubleSpinBox(self.fiveSize)
        self.doubleSpinBox_19.setMinimum(-10.0)
        self.doubleSpinBox_19.setMaximum(10.0)
        self.doubleSpinBox_19.setSingleStep(0.05)
        self.doubleSpinBox_19.setObjectName("doubleSpinBox_19")
        self.verticalLayout_6.addWidget(self.doubleSpinBox_19)
        self.doubleSpinBox_20 = QtWidgets.QDoubleSpinBox(self.fiveSize)
        self.doubleSpinBox_20.setMinimum(-10.0)
        self.doubleSpinBox_20.setMaximum(10.0)
        self.doubleSpinBox_20.setSingleStep(0.05)
        self.doubleSpinBox_20.setObjectName("doubleSpinBox_20")
        self.verticalLayout_6.addWidget(self.doubleSpinBox_20)
        self.doubleSpinBox_21 = QtWidgets.QDoubleSpinBox(self.fiveSize)
        self.doubleSpinBox_21.setMinimum(-10.0)
        self.doubleSpinBox_21.setMaximum(10.0)
        self.doubleSpinBox_21.setSingleStep(0.05)
        self.doubleSpinBox_21.setObjectName("doubleSpinBox_21")
        self.verticalLayout_6.addWidget(self.doubleSpinBox_21)
        self.doubleSpinBox_22 = QtWidgets.QDoubleSpinBox(self.fiveSize)
        self.doubleSpinBox_22.setMinimum(-10.0)
        self.doubleSpinBox_22.setMaximum(10.0)
        self.doubleSpinBox_22.setSingleStep(0.05)
        self.doubleSpinBox_22.setObjectName("doubleSpinBox_22")
        self.verticalLayout_6.addWidget(self.doubleSpinBox_22)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.doubleSpinBox_23 = QtWidgets.QDoubleSpinBox(self.fiveSize)
        self.doubleSpinBox_23.setMinimum(-10.0)
        self.doubleSpinBox_23.setMaximum(10.0)
        self.doubleSpinBox_23.setSingleStep(0.05)
        self.doubleSpinBox_23.setObjectName("doubleSpinBox_23")
        self.verticalLayout_7.addWidget(self.doubleSpinBox_23)
        self.doubleSpinBox_24 = QtWidgets.QDoubleSpinBox(self.fiveSize)
        self.doubleSpinBox_24.setMinimum(-10.0)
        self.doubleSpinBox_24.setMaximum(10.0)
        self.doubleSpinBox_24.setSingleStep(0.05)
        self.doubleSpinBox_24.setObjectName("doubleSpinBox_24")
        self.verticalLayout_7.addWidget(self.doubleSpinBox_24)
        self.doubleSpinBox_25 = QtWidgets.QDoubleSpinBox(self.fiveSize)
        self.doubleSpinBox_25.setMinimum(-10.0)
        self.doubleSpinBox_25.setMaximum(10.0)
        self.doubleSpinBox_25.setSingleStep(0.05)
        self.doubleSpinBox_25.setObjectName("doubleSpinBox_25")
        self.verticalLayout_7.addWidget(self.doubleSpinBox_25)
        self.doubleSpinBox_26 = QtWidgets.QDoubleSpinBox(self.fiveSize)
        self.doubleSpinBox_26.setMinimum(-10.0)
        self.doubleSpinBox_26.setMaximum(10.0)
        self.doubleSpinBox_26.setSingleStep(0.05)
        self.doubleSpinBox_26.setObjectName("doubleSpinBox_26")
        self.verticalLayout_7.addWidget(self.doubleSpinBox_26)
        self.doubleSpinBox_27 = QtWidgets.QDoubleSpinBox(self.fiveSize)
        self.doubleSpinBox_27.setMinimum(-10.0)
        self.doubleSpinBox_27.setMaximum(10.0)
        self.doubleSpinBox_27.setSingleStep(0.05)
        self.doubleSpinBox_27.setObjectName("doubleSpinBox_27")
        self.verticalLayout_7.addWidget(self.doubleSpinBox_27)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.doubleSpinBox_28 = QtWidgets.QDoubleSpinBox(self.fiveSize)
        self.doubleSpinBox_28.setMinimum(-10.0)
        self.doubleSpinBox_28.setMaximum(10.0)
        self.doubleSpinBox_28.setSingleStep(0.05)
        self.doubleSpinBox_28.setObjectName("doubleSpinBox_28")
        self.verticalLayout_8.addWidget(self.doubleSpinBox_28)
        self.doubleSpinBox_29 = QtWidgets.QDoubleSpinBox(self.fiveSize)
        self.doubleSpinBox_29.setMinimum(-10.0)
        self.doubleSpinBox_29.setMaximum(10.0)
        self.doubleSpinBox_29.setSingleStep(0.05)
        self.doubleSpinBox_29.setObjectName("doubleSpinBox_29")
        self.verticalLayout_8.addWidget(self.doubleSpinBox_29)
        self.doubleSpinBox_30 = QtWidgets.QDoubleSpinBox(self.fiveSize)
        self.doubleSpinBox_30.setMinimum(-10.0)
        self.doubleSpinBox_30.setMaximum(10.0)
        self.doubleSpinBox_30.setSingleStep(0.05)
        self.doubleSpinBox_30.setObjectName("doubleSpinBox_30")
        self.verticalLayout_8.addWidget(self.doubleSpinBox_30)
        self.doubleSpinBox_31 = QtWidgets.QDoubleSpinBox(self.fiveSize)
        self.doubleSpinBox_31.setMinimum(-10.0)
        self.doubleSpinBox_31.setMaximum(10.0)
        self.doubleSpinBox_31.setSingleStep(0.05)
        self.doubleSpinBox_31.setObjectName("doubleSpinBox_31")
        self.verticalLayout_8.addWidget(self.doubleSpinBox_31)
        self.doubleSpinBox_32 = QtWidgets.QDoubleSpinBox(self.fiveSize)
        self.doubleSpinBox_32.setMinimum(-10.0)
        self.doubleSpinBox_32.setMaximum(10.0)
        self.doubleSpinBox_32.setSingleStep(0.05)
        self.doubleSpinBox_32.setObjectName("doubleSpinBox_32")
        self.verticalLayout_8.addWidget(self.doubleSpinBox_32)
        self.horizontalLayout_3.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.doubleSpinBox_33 = QtWidgets.QDoubleSpinBox(self.fiveSize)
        self.doubleSpinBox_33.setMinimum(-10.0)
        self.doubleSpinBox_33.setMaximum(10.0)
        self.doubleSpinBox_33.setSingleStep(0.05)
        self.doubleSpinBox_33.setObjectName("doubleSpinBox_33")
        self.verticalLayout_9.addWidget(self.doubleSpinBox_33)
        self.doubleSpinBox_34 = QtWidgets.QDoubleSpinBox(self.fiveSize)
        self.doubleSpinBox_34.setMinimum(-10.0)
        self.doubleSpinBox_34.setMaximum(10.0)
        self.doubleSpinBox_34.setSingleStep(0.05)
        self.doubleSpinBox_34.setObjectName("doubleSpinBox_34")
        self.verticalLayout_9.addWidget(self.doubleSpinBox_34)
        self.doubleSpinBox_35 = QtWidgets.QDoubleSpinBox(self.fiveSize)
        self.doubleSpinBox_35.setMinimum(-10.0)
        self.doubleSpinBox_35.setMaximum(10.0)
        self.doubleSpinBox_35.setSingleStep(0.05)
        self.doubleSpinBox_35.setObjectName("doubleSpinBox_35")
        self.verticalLayout_9.addWidget(self.doubleSpinBox_35)
        self.doubleSpinBox_36 = QtWidgets.QDoubleSpinBox(self.fiveSize)
        self.doubleSpinBox_36.setMinimum(-10.0)
        self.doubleSpinBox_36.setMaximum(10.0)
        self.doubleSpinBox_36.setSingleStep(0.05)
        self.doubleSpinBox_36.setObjectName("doubleSpinBox_36")
        self.verticalLayout_9.addWidget(self.doubleSpinBox_36)
        self.doubleSpinBox_37 = QtWidgets.QDoubleSpinBox(self.fiveSize)
        self.doubleSpinBox_37.setMinimum(-10.0)
        self.doubleSpinBox_37.setMaximum(10.0)
        self.doubleSpinBox_37.setSingleStep(0.05)
        self.doubleSpinBox_37.setObjectName("doubleSpinBox_37")
        self.verticalLayout_9.addWidget(self.doubleSpinBox_37)
        self.horizontalLayout_3.addLayout(self.verticalLayout_9)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_3)
        self.tabWidget.addTab(self.fiveSize, "")
        self.sevenSize = QtWidgets.QWidget()
        self.sevenSize.setObjectName("sevenSize")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.sevenSize)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.doubleSpinBox_44 = QtWidgets.QDoubleSpinBox(self.sevenSize)
        self.doubleSpinBox_44.setMinimum(-10.0)
        self.doubleSpinBox_44.setMaximum(10.0)
        self.doubleSpinBox_44.setSingleStep(0.05)
        self.doubleSpinBox_44.setObjectName("doubleSpinBox_44")
        self.verticalLayout_10.addWidget(self.doubleSpinBox_44)
        self.doubleSpinBox_38 = QtWidgets.QDoubleSpinBox(self.sevenSize)
        self.doubleSpinBox_38.setMinimum(-10.0)
        self.doubleSpinBox_38.setMaximum(10.0)
        self.doubleSpinBox_38.setSingleStep(0.05)
        self.doubleSpinBox_38.setObjectName("doubleSpinBox_38")
        self.verticalLayout_10.addWidget(self.doubleSpinBox_38)
        self.doubleSpinBox_39 = QtWidgets.QDoubleSpinBox(self.sevenSize)
        self.doubleSpinBox_39.setMinimum(-10.0)
        self.doubleSpinBox_39.setMaximum(10.0)
        self.doubleSpinBox_39.setSingleStep(0.05)
        self.doubleSpinBox_39.setObjectName("doubleSpinBox_39")
        self.verticalLayout_10.addWidget(self.doubleSpinBox_39)
        self.doubleSpinBox_40 = QtWidgets.QDoubleSpinBox(self.sevenSize)
        self.doubleSpinBox_40.setMinimum(-10.0)
        self.doubleSpinBox_40.setMaximum(10.0)
        self.doubleSpinBox_40.setSingleStep(0.05)
        self.doubleSpinBox_40.setObjectName("doubleSpinBox_40")
        self.verticalLayout_10.addWidget(self.doubleSpinBox_40)
        self.doubleSpinBox_41 = QtWidgets.QDoubleSpinBox(self.sevenSize)
        self.doubleSpinBox_41.setMinimum(-10.0)
        self.doubleSpinBox_41.setMaximum(10.0)
        self.doubleSpinBox_41.setSingleStep(0.05)
        self.doubleSpinBox_41.setObjectName("doubleSpinBox_41")
        self.verticalLayout_10.addWidget(self.doubleSpinBox_41)
        self.doubleSpinBox_42 = QtWidgets.QDoubleSpinBox(self.sevenSize)
        self.doubleSpinBox_42.setMinimum(-10.0)
        self.doubleSpinBox_42.setMaximum(10.0)
        self.doubleSpinBox_42.setSingleStep(0.05)
        self.doubleSpinBox_42.setObjectName("doubleSpinBox_42")
        self.verticalLayout_10.addWidget(self.doubleSpinBox_42)
        self.doubleSpinBox_43 = QtWidgets.QDoubleSpinBox(self.sevenSize)
        self.doubleSpinBox_43.setMinimum(-10.0)
        self.doubleSpinBox_43.setMaximum(10.0)
        self.doubleSpinBox_43.setSingleStep(0.05)
        self.doubleSpinBox_43.setObjectName("doubleSpinBox_43")
        self.verticalLayout_10.addWidget(self.doubleSpinBox_43)
        self.horizontalLayout_4.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.doubleSpinBox_45 = QtWidgets.QDoubleSpinBox(self.sevenSize)
        self.doubleSpinBox_45.setMinimum(-10.0)
        self.doubleSpinBox_45.setMaximum(10.0)
        self.doubleSpinBox_45.setSingleStep(0.05)
        self.doubleSpinBox_45.setObjectName("doubleSpinBox_45")
        self.verticalLayout_11.addWidget(self.doubleSpinBox_45)
        self.doubleSpinBox_46 = QtWidgets.QDoubleSpinBox(self.sevenSize)
        self.doubleSpinBox_46.setMinimum(-10.0)
        self.doubleSpinBox_46.setMaximum(10.0)
        self.doubleSpinBox_46.setSingleStep(0.05)
        self.doubleSpinBox_46.setObjectName("doubleSpinBox_46")
        self.verticalLayout_11.addWidget(self.doubleSpinBox_46)
        self.doubleSpinBox_47 = QtWidgets.QDoubleSpinBox(self.sevenSize)
        self.doubleSpinBox_47.setMinimum(-10.0)
        self.doubleSpinBox_47.setMaximum(10.0)
        self.doubleSpinBox_47.setSingleStep(0.05)
        self.doubleSpinBox_47.setObjectName("doubleSpinBox_47")
        self.verticalLayout_11.addWidget(self.doubleSpinBox_47)
        self.doubleSpinBox_48 = QtWidgets.QDoubleSpinBox(self.sevenSize)
        self.doubleSpinBox_48.setMinimum(-10.0)
        self.doubleSpinBox_48.setMaximum(10.0)
        self.doubleSpinBox_48.setSingleStep(0.05)
        self.doubleSpinBox_48.setObjectName("doubleSpinBox_48")
        self.verticalLayout_11.addWidget(self.doubleSpinBox_48)
        self.doubleSpinBox_49 = QtWidgets.QDoubleSpinBox(self.sevenSize)
        self.doubleSpinBox_49.setMinimum(-10.0)
        self.doubleSpinBox_49.setMaximum(10.0)
        self.doubleSpinBox_49.setSingleStep(0.05)
        self.doubleSpinBox_49.setObjectName("doubleSpinBox_49")
        self.verticalLayout_11.addWidget(self.doubleSpinBox_49)
        self.doubleSpinBox_50 = QtWidgets.QDoubleSpinBox(self.sevenSize)
        self.doubleSpinBox_50.setMinimum(-10.0)
        self.doubleSpinBox_50.setMaximum(10.0)
        self.doubleSpinBox_50.setSingleStep(0.05)
        self.doubleSpinBox_50.setObjectName("doubleSpinBox_50")
        self.verticalLayout_11.addWidget(self.doubleSpinBox_50)
        self.doubleSpinBox_51 = QtWidgets.QDoubleSpinBox(self.sevenSize)
        self.doubleSpinBox_51.setMinimum(-10.0)
        self.doubleSpinBox_51.setMaximum(10.0)
        self.doubleSpinBox_51.setSingleStep(0.05)
        self.doubleSpinBox_51.setObjectName("doubleSpinBox_51")
        self.verticalLayout_11.addWidget(self.doubleSpinBox_51)
        self.horizontalLayout_4.addLayout(self.verticalLayout_11)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.doubleSpinBox_52 = QtWidgets.QDoubleSpinBox(self.sevenSize)
        self.doubleSpinBox_52.setMinimum(-10.0)
        self.doubleSpinBox_52.setMaximum(10.0)
        self.doubleSpinBox_52.setSingleStep(0.05)
        self.doubleSpinBox_52.setObjectName("doubleSpinBox_52")
        self.verticalLayout_12.addWidget(self.doubleSpinBox_52)
        self.doubleSpinBox_53 = QtWidgets.QDoubleSpinBox(self.sevenSize)
        self.doubleSpinBox_53.setMinimum(-10.0)
        self.doubleSpinBox_53.setMaximum(10.0)
        self.doubleSpinBox_53.setSingleStep(0.05)
        self.doubleSpinBox_53.setObjectName("doubleSpinBox_53")
        self.verticalLayout_12.addWidget(self.doubleSpinBox_53)
        self.doubleSpinBox_54 = QtWidgets.QDoubleSpinBox(self.sevenSize)
        self.doubleSpinBox_54.setMinimum(-10.0)
        self.doubleSpinBox_54.setMaximum(10.0)
        self.doubleSpinBox_54.setSingleStep(0.05)
        self.doubleSpinBox_54.setObjectName("doubleSpinBox_54")
        self.verticalLayout_12.addWidget(self.doubleSpinBox_54)
        self.doubleSpinBox_55 = QtWidgets.QDoubleSpinBox(self.sevenSize)
        self.doubleSpinBox_55.setMinimum(-10.0)
        self.doubleSpinBox_55.setMaximum(10.0)
        self.doubleSpinBox_55.setSingleStep(0.05)
        self.doubleSpinBox_55.setObjectName("doubleSpinBox_55")
        self.verticalLayout_12.addWidget(self.doubleSpinBox_55)
        self.doubleSpinBox_56 = QtWidgets.QDoubleSpinBox(self.sevenSize)
        self.doubleSpinBox_56.setMinimum(-10.0)
        self.doubleSpinBox_56.setMaximum(10.0)
        self.doubleSpinBox_56.setSingleStep(0.05)
        self.doubleSpinBox_56.setObjectName("doubleSpinBox_56")
        self.verticalLayout_12.addWidget(self.doubleSpinBox_56)
        self.doubleSpinBox_57 = QtWidgets.QDoubleSpinBox(self.sevenSize)
        self.doubleSpinBox_57.setMinimum(-10.0)
        self.doubleSpinBox_57.setMaximum(10.0)
        self.doubleSpinBox_57.setSingleStep(0.05)
        self.doubleSpinBox_57.setObjectName("doubleSpinBox_57")
        self.verticalLayout_12.addWidget(self.doubleSpinBox_57)
        self.doubleSpinBox_58 = QtWidgets.QDoubleSpinBox(self.sevenSize)
        self.doubleSpinBox_58.setMinimum(-10.0)
        self.doubleSpinBox_58.setMaximum(10.0)
        self.doubleSpinBox_58.setSingleStep(0.05)
        self.doubleSpinBox_58.setObjectName("doubleSpinBox_58")
        self.verticalLayout_12.addWidget(self.doubleSpinBox_58)
        self.horizontalLayout_4.addLayout(self.verticalLayout_12)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.doubleSpinBox_59 = QtWidgets.QDoubleSpinBox(self.sevenSize)
        self.doubleSpinBox_59.setMinimum(-10.0)
        self.doubleSpinBox_59.setMaximum(10.0)
        self.doubleSpinBox_59.setSingleStep(0.05)
        self.doubleSpinBox_59.setObjectName("doubleSpinBox_59")
        self.verticalLayout_13.addWidget(self.doubleSpinBox_59)
        self.doubleSpinBox_60 = QtWidgets.QDoubleSpinBox(self.sevenSize)
        self.doubleSpinBox_60.setMinimum(-10.0)
        self.doubleSpinBox_60.setMaximum(10.0)
        self.doubleSpinBox_60.setSingleStep(0.05)
        self.doubleSpinBox_60.setObjectName("doubleSpinBox_60")
        self.verticalLayout_13.addWidget(self.doubleSpinBox_60)
        self.doubleSpinBox_61 = QtWidgets.QDoubleSpinBox(self.sevenSize)
        self.doubleSpinBox_61.setMinimum(-10.0)
        self.doubleSpinBox_61.setMaximum(10.0)
        self.doubleSpinBox_61.setSingleStep(0.05)
        self.doubleSpinBox_61.setObjectName("doubleSpinBox_61")
        self.verticalLayout_13.addWidget(self.doubleSpinBox_61)
        self.doubleSpinBox_62 = QtWidgets.QDoubleSpinBox(self.sevenSize)
        self.doubleSpinBox_62.setMinimum(-10.0)
        self.doubleSpinBox_62.setMaximum(10.0)
        self.doubleSpinBox_62.setSingleStep(0.05)
        self.doubleSpinBox_62.setObjectName("doubleSpinBox_62")
        self.verticalLayout_13.addWidget(self.doubleSpinBox_62)
        self.doubleSpinBox_63 = QtWidgets.QDoubleSpinBox(self.sevenSize)
        self.doubleSpinBox_63.setMinimum(-10.0)
        self.doubleSpinBox_63.setMaximum(10.0)
        self.doubleSpinBox_63.setSingleStep(0.05)
        self.doubleSpinBox_63.setObjectName("doubleSpinBox_63")
        self.verticalLayout_13.addWidget(self.doubleSpinBox_63)
        self.doubleSpinBox_64 = QtWidgets.QDoubleSpinBox(self.sevenSize)
        self.doubleSpinBox_64.setMinimum(-10.0)
        self.doubleSpinBox_64.setMaximum(10.0)
        self.doubleSpinBox_64.setSingleStep(0.05)
        self.doubleSpinBox_64.setObjectName("doubleSpinBox_64")
        self.verticalLayout_13.addWidget(self.doubleSpinBox_64)
        self.doubleSpinBox_65 = QtWidgets.QDoubleSpinBox(self.sevenSize)
        self.doubleSpinBox_65.setMinimum(-10.0)
        self.doubleSpinBox_65.setMaximum(10.0)
        self.doubleSpinBox_65.setSingleStep(0.05)
        self.doubleSpinBox_65.setObjectName("doubleSpinBox_65")
        self.verticalLayout_13.addWidget(self.doubleSpinBox_65)
        self.horizontalLayout_4.addLayout(self.verticalLayout_13)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.doubleSpinBox_66 = QtWidgets.QDoubleSpinBox(self.sevenSize)
        self.doubleSpinBox_66.setMinimum(-10.0)
        self.doubleSpinBox_66.setMaximum(10.0)
        self.doubleSpinBox_66.setSingleStep(0.05)
        self.doubleSpinBox_66.setObjectName("doubleSpinBox_66")
        self.verticalLayout_14.addWidget(self.doubleSpinBox_66)
        self.doubleSpinBox_67 = QtWidgets.QDoubleSpinBox(self.sevenSize)
        self.doubleSpinBox_67.setMinimum(-10.0)
        self.doubleSpinBox_67.setMaximum(10.0)
        self.doubleSpinBox_67.setSingleStep(0.05)
        self.doubleSpinBox_67.setObjectName("doubleSpinBox_67")
        self.verticalLayout_14.addWidget(self.doubleSpinBox_67)
        self.doubleSpinBox_68 = QtWidgets.QDoubleSpinBox(self.sevenSize)
        self.doubleSpinBox_68.setMinimum(-10.0)
        self.doubleSpinBox_68.setMaximum(10.0)
        self.doubleSpinBox_68.setSingleStep(0.05)
        self.doubleSpinBox_68.setObjectName("doubleSpinBox_68")
        self.verticalLayout_14.addWidget(self.doubleSpinBox_68)
        self.doubleSpinBox_69 = QtWidgets.QDoubleSpinBox(self.sevenSize)
        self.doubleSpinBox_69.setMinimum(-10.0)
        self.doubleSpinBox_69.setMaximum(10.0)
        self.doubleSpinBox_69.setSingleStep(0.05)
        self.doubleSpinBox_69.setObjectName("doubleSpinBox_69")
        self.verticalLayout_14.addWidget(self.doubleSpinBox_69)
        self.doubleSpinBox_70 = QtWidgets.QDoubleSpinBox(self.sevenSize)
        self.doubleSpinBox_70.setMinimum(-10.0)
        self.doubleSpinBox_70.setMaximum(10.0)
        self.doubleSpinBox_70.setSingleStep(0.05)
        self.doubleSpinBox_70.setObjectName("doubleSpinBox_70")
        self.verticalLayout_14.addWidget(self.doubleSpinBox_70)
        self.doubleSpinBox_71 = QtWidgets.QDoubleSpinBox(self.sevenSize)
        self.doubleSpinBox_71.setMinimum(-10.0)
        self.doubleSpinBox_71.setMaximum(10.0)
        self.doubleSpinBox_71.setSingleStep(0.05)
        self.doubleSpinBox_71.setObjectName("doubleSpinBox_71")
        self.verticalLayout_14.addWidget(self.doubleSpinBox_71)
        self.doubleSpinBox_72 = QtWidgets.QDoubleSpinBox(self.sevenSize)
        self.doubleSpinBox_72.setMinimum(-10.0)
        self.doubleSpinBox_72.setMaximum(10.0)
        self.doubleSpinBox_72.setSingleStep(0.05)
        self.doubleSpinBox_72.setObjectName("doubleSpinBox_72")
        self.verticalLayout_14.addWidget(self.doubleSpinBox_72)
        self.horizontalLayout_4.addLayout(self.verticalLayout_14)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.doubleSpinBox_73 = QtWidgets.QDoubleSpinBox(self.sevenSize)
        self.doubleSpinBox_73.setMinimum(-10.0)
        self.doubleSpinBox_73.setMaximum(10.0)
        self.doubleSpinBox_73.setSingleStep(0.05)
        self.doubleSpinBox_73.setObjectName("doubleSpinBox_73")
        self.verticalLayout_15.addWidget(self.doubleSpinBox_73)
        self.doubleSpinBox_74 = QtWidgets.QDoubleSpinBox(self.sevenSize)
        self.doubleSpinBox_74.setMinimum(-10.0)
        self.doubleSpinBox_74.setMaximum(10.0)
        self.doubleSpinBox_74.setSingleStep(0.05)
        self.doubleSpinBox_74.setObjectName("doubleSpinBox_74")
        self.verticalLayout_15.addWidget(self.doubleSpinBox_74)
        self.doubleSpinBox_75 = QtWidgets.QDoubleSpinBox(self.sevenSize)
        self.doubleSpinBox_75.setMinimum(-10.0)
        self.doubleSpinBox_75.setMaximum(10.0)
        self.doubleSpinBox_75.setSingleStep(0.05)
        self.doubleSpinBox_75.setObjectName("doubleSpinBox_75")
        self.verticalLayout_15.addWidget(self.doubleSpinBox_75)
        self.doubleSpinBox_76 = QtWidgets.QDoubleSpinBox(self.sevenSize)
        self.doubleSpinBox_76.setMinimum(-10.0)
        self.doubleSpinBox_76.setMaximum(10.0)
        self.doubleSpinBox_76.setSingleStep(0.05)
        self.doubleSpinBox_76.setObjectName("doubleSpinBox_76")
        self.verticalLayout_15.addWidget(self.doubleSpinBox_76)
        self.doubleSpinBox_77 = QtWidgets.QDoubleSpinBox(self.sevenSize)
        self.doubleSpinBox_77.setMinimum(-10.0)
        self.doubleSpinBox_77.setMaximum(10.0)
        self.doubleSpinBox_77.setSingleStep(0.05)
        self.doubleSpinBox_77.setObjectName("doubleSpinBox_77")
        self.verticalLayout_15.addWidget(self.doubleSpinBox_77)
        self.doubleSpinBox_78 = QtWidgets.QDoubleSpinBox(self.sevenSize)
        self.doubleSpinBox_78.setMinimum(-10.0)
        self.doubleSpinBox_78.setMaximum(10.0)
        self.doubleSpinBox_78.setSingleStep(0.05)
        self.doubleSpinBox_78.setObjectName("doubleSpinBox_78")
        self.verticalLayout_15.addWidget(self.doubleSpinBox_78)
        self.doubleSpinBox_79 = QtWidgets.QDoubleSpinBox(self.sevenSize)
        self.doubleSpinBox_79.setMinimum(-10.0)
        self.doubleSpinBox_79.setMaximum(10.0)
        self.doubleSpinBox_79.setSingleStep(0.05)
        self.doubleSpinBox_79.setObjectName("doubleSpinBox_79")
        self.verticalLayout_15.addWidget(self.doubleSpinBox_79)
        self.horizontalLayout_4.addLayout(self.verticalLayout_15)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.doubleSpinBox_80 = QtWidgets.QDoubleSpinBox(self.sevenSize)
        self.doubleSpinBox_80.setMinimum(-10.0)
        self.doubleSpinBox_80.setMaximum(10.0)
        self.doubleSpinBox_80.setSingleStep(0.05)
        self.doubleSpinBox_80.setObjectName("doubleSpinBox_80")
        self.verticalLayout_16.addWidget(self.doubleSpinBox_80)
        self.doubleSpinBox_81 = QtWidgets.QDoubleSpinBox(self.sevenSize)
        self.doubleSpinBox_81.setMinimum(-10.0)
        self.doubleSpinBox_81.setMaximum(10.0)
        self.doubleSpinBox_81.setSingleStep(0.05)
        self.doubleSpinBox_81.setObjectName("doubleSpinBox_81")
        self.verticalLayout_16.addWidget(self.doubleSpinBox_81)
        self.doubleSpinBox_82 = QtWidgets.QDoubleSpinBox(self.sevenSize)
        self.doubleSpinBox_82.setMinimum(-10.0)
        self.doubleSpinBox_82.setMaximum(10.0)
        self.doubleSpinBox_82.setSingleStep(0.05)
        self.doubleSpinBox_82.setObjectName("doubleSpinBox_82")
        self.verticalLayout_16.addWidget(self.doubleSpinBox_82)
        self.doubleSpinBox_83 = QtWidgets.QDoubleSpinBox(self.sevenSize)
        self.doubleSpinBox_83.setMinimum(-10.0)
        self.doubleSpinBox_83.setMaximum(10.0)
        self.doubleSpinBox_83.setSingleStep(0.05)
        self.doubleSpinBox_83.setObjectName("doubleSpinBox_83")
        self.verticalLayout_16.addWidget(self.doubleSpinBox_83)
        self.doubleSpinBox_84 = QtWidgets.QDoubleSpinBox(self.sevenSize)
        self.doubleSpinBox_84.setMinimum(-10.0)
        self.doubleSpinBox_84.setMaximum(10.0)
        self.doubleSpinBox_84.setSingleStep(0.05)
        self.doubleSpinBox_84.setObjectName("doubleSpinBox_84")
        self.verticalLayout_16.addWidget(self.doubleSpinBox_84)
        self.doubleSpinBox_85 = QtWidgets.QDoubleSpinBox(self.sevenSize)
        self.doubleSpinBox_85.setMinimum(-10.0)
        self.doubleSpinBox_85.setMaximum(10.0)
        self.doubleSpinBox_85.setSingleStep(0.05)
        self.doubleSpinBox_85.setObjectName("doubleSpinBox_85")
        self.verticalLayout_16.addWidget(self.doubleSpinBox_85)
        self.doubleSpinBox_86 = QtWidgets.QDoubleSpinBox(self.sevenSize)
        self.doubleSpinBox_86.setMinimum(-10.0)
        self.doubleSpinBox_86.setMaximum(10.0)
        self.doubleSpinBox_86.setSingleStep(0.05)
        self.doubleSpinBox_86.setObjectName("doubleSpinBox_86")
        self.verticalLayout_16.addWidget(self.doubleSpinBox_86)
        self.horizontalLayout_4.addLayout(self.verticalLayout_16)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_4)
        self.tabWidget.addTab(self.sevenSize, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setDefault(True)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_4.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_4.addWidget(self.pushButton_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_4)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.threeSize), _translate("Dialog", "3×3"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.fiveSize), _translate("Dialog", "5×5"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.sevenSize), _translate("Dialog", "7×7"))
        self.pushButton.setText(_translate("Dialog", "確認"))
        self.pushButton.setShortcut(_translate("Dialog", "Return"))
        self.pushButton_2.setText(_translate("Dialog", "取消"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
