# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(602, 430)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(1920, 1080))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMaximumSize(QtCore.QSize(19200, 10800))
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.graphicsView = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setText("")
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout_2.addWidget(self.graphicsView)
        self.horizontalLayout.addWidget(self.groupBox)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.typeSelection = QtWidgets.QComboBox(self.groupBox_3)
        self.typeSelection.setObjectName("typeSelection")
        self.typeSelection.addItem("")
        self.typeSelection.addItem("")
        self.typeSelection.addItem("")
        self.typeSelection.addItem("")
        self.horizontalLayout_3.addWidget(self.typeSelection)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.threeSizeRadioButton = QtWidgets.QRadioButton(self.groupBox_3)
        self.threeSizeRadioButton.setObjectName("threeSizeRadioButton")
        self.horizontalLayout_5.addWidget(self.threeSizeRadioButton)
        self.fiveSizeRadioButton = QtWidgets.QRadioButton(self.groupBox_3)
        self.fiveSizeRadioButton.setChecked(True)
        self.fiveSizeRadioButton.setObjectName("fiveSizeRadioButton")
        self.horizontalLayout_5.addWidget(self.fiveSizeRadioButton)
        self.sevenSizeRadioButton = QtWidgets.QRadioButton(self.groupBox_3)
        self.sevenSizeRadioButton.setObjectName("sevenSizeRadioButton")
        self.horizontalLayout_5.addWidget(self.sevenSizeRadioButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.previewKernelButton = QtWidgets.QPushButton(self.groupBox_3)
        self.previewKernelButton.setObjectName("previewKernelButton")
        self.horizontalLayout_4.addWidget(self.previewKernelButton)
        self.editKernelButton = QtWidgets.QPushButton(self.groupBox_3)
        self.editKernelButton.setObjectName("editKernelButton")
        self.horizontalLayout_4.addWidget(self.editKernelButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.applyConvolutionButton = QtWidgets.QPushButton(self.groupBox_2)
        self.applyConvolutionButton.setDefault(True)
        self.applyConvolutionButton.setObjectName("applyConvolutionButton")
        self.horizontalLayout_6.addWidget(self.applyConvolutionButton)
        self.resetButton = QtWidgets.QPushButton(self.groupBox_2)
        self.resetButton.setObjectName("resetButton")
        self.horizontalLayout_6.addWidget(self.resetButton)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 602, 22))
        self.menubar.setObjectName("menubar")
        self.menuMain_Window = QtWidgets.QMenu(self.menubar)
        self.menuMain_Window.setObjectName("menuMain_Window")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionImportImage = QtWidgets.QAction(MainWindow)
        self.actionImportImage.setObjectName("actionImportImage")
        self.actionExportImage = QtWidgets.QAction(MainWindow)
        self.actionExportImage.setObjectName("actionExportImage")
        self.actionShowAbout = QtWidgets.QAction(MainWindow)
        self.actionShowAbout.setObjectName("actionShowAbout")
        self.menuMain_Window.addAction(self.actionImportImage)
        self.menuMain_Window.addAction(self.actionExportImage)
        self.menu_2.addAction(self.actionShowAbout)
        self.menubar.addAction(self.menuMain_Window.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SE-342::Morphological Example"))
        self.groupBox.setTitle(_translate("MainWindow", "預覽"))
        self.groupBox_3.setTitle(_translate("MainWindow", "變數設定"))
        self.label.setText(_translate("MainWindow", "採用"))
        self.typeSelection.setItemText(0, _translate("MainWindow", "形態學邊緣檢測"))
        self.typeSelection.setItemText(1, _translate("MainWindow", "條件膨脹（二值圖）"))
        self.typeSelection.setItemText(2, _translate("MainWindow", "形態學重建（灰度圖）"))
        self.typeSelection.setItemText(3, _translate("MainWindow", "形態學梯度"))
        self.label_3.setText(_translate("MainWindow", "卷積核尺寸:"))
        self.threeSizeRadioButton.setText(_translate("MainWindow", "3×3"))
        self.fiveSizeRadioButton.setText(_translate("MainWindow", "5×5"))
        self.sevenSizeRadioButton.setText(_translate("MainWindow", "7×7"))
        self.label_2.setText(_translate("MainWindow", "卷積核形狀:"))
        self.previewKernelButton.setText(_translate("MainWindow", "預覽"))
        self.editKernelButton.setText(_translate("MainWindow", "變更⋯"))
        self.groupBox_2.setTitle(_translate("MainWindow", "控制鈕"))
        self.applyConvolutionButton.setText(_translate("MainWindow", "應用"))
        self.applyConvolutionButton.setShortcut(_translate("MainWindow", "Return"))
        self.resetButton.setText(_translate("MainWindow", "重置"))
        self.menuMain_Window.setTitle(_translate("MainWindow", "檔案"))
        self.menu_2.setTitle(_translate("MainWindow", "說明"))
        self.actionImportImage.setText(_translate("MainWindow", "匯入圖片檔"))
        self.actionImportImage.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionExportImage.setText(_translate("MainWindow", "匯出圖片檔"))
        self.actionExportImage.setToolTip(_translate("MainWindow", "匯入圖片檔"))
        self.actionExportImage.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionShowAbout.setText(_translate("MainWindow", "詳情"))
        self.actionShowAbout.setToolTip(_translate("MainWindow", "App 版本"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
