# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(602, 430)
        MainWindow.setMaximumSize(QtCore.QSize(720, 480))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMaximumSize(QtCore.QSize(720, 480))
        self.groupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.graphicsView = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setText("")
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout_2.addWidget(self.graphicsView)
        self.horizontalLayout.addWidget(self.groupBox)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.kernelSizeLabel = QtWidgets.QLabel(self.groupBox_3)
        self.kernelSizeLabel.setObjectName("kernelSizeLabel")
        self.horizontalLayout_5.addWidget(self.kernelSizeLabel)
        self.kernelSizeSlider = QtWidgets.QSlider(self.groupBox_3)
        self.kernelSizeSlider.setMinimum(3)
        self.kernelSizeSlider.setMaximum(13)
        self.kernelSizeSlider.setSingleStep(2)
        self.kernelSizeSlider.setPageStep(3)
        self.kernelSizeSlider.setProperty("value", 5)
        self.kernelSizeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.kernelSizeSlider.setObjectName("kernelSizeSlider")
        self.horizontalLayout_5.addWidget(self.kernelSizeSlider)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.sigmaSizeLabel = QtWidgets.QLabel(self.groupBox_3)
        self.sigmaSizeLabel.setObjectName("sigmaSizeLabel")
        self.horizontalLayout_4.addWidget(self.sigmaSizeLabel)
        self.sigmaSizeSlider = QtWidgets.QSlider(self.groupBox_3)
        self.sigmaSizeSlider.setMinimum(1)
        self.sigmaSizeSlider.setMaximum(100)
        self.sigmaSizeSlider.setProperty("value", 50)
        self.sigmaSizeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.sigmaSizeSlider.setObjectName("sigmaSizeSlider")
        self.horizontalLayout_4.addWidget(self.sigmaSizeSlider)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_3.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton.setEnabled(False)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_3.addWidget(self.pushButton)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_3.addWidget(self.pushButton_3)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 602, 22))
        self.menubar.setObjectName("menubar")
        self.menuMain_Window = QtWidgets.QMenu(self.menubar)
        self.menuMain_Window.setObjectName("menuMain_Window")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionImportImage = QtWidgets.QAction(MainWindow)
        self.actionImportImage.setObjectName("actionImportImage")
        self.actionExportImage = QtWidgets.QAction(MainWindow)
        self.actionExportImage.setObjectName("actionExportImage")
        self.actionResume = QtWidgets.QAction(MainWindow)
        self.actionResume.setObjectName("actionResume")
        self.actionZoomIn = QtWidgets.QAction(MainWindow)
        self.actionZoomIn.setObjectName("actionZoomIn")
        self.actionZoomOut = QtWidgets.QAction(MainWindow)
        self.actionZoomOut.setObjectName("actionZoomOut")
        self.actionReset = QtWidgets.QAction(MainWindow)
        self.actionReset.setObjectName("actionReset")
        self.actionShowAbout = QtWidgets.QAction(MainWindow)
        self.actionShowAbout.setObjectName("actionShowAbout")
        self.menuMain_Window.addAction(self.actionImportImage)
        self.menuMain_Window.addAction(self.actionExportImage)
        self.menuMain_Window.addSeparator()
        self.menuMain_Window.addAction(self.actionResume)
        self.menu_2.addAction(self.actionShowAbout)
        self.menu_3.addAction(self.actionZoomIn)
        self.menu_3.addAction(self.actionZoomOut)
        self.menu_3.addSeparator()
        self.menu_3.addAction(self.actionReset)
        self.menubar.addAction(self.menuMain_Window.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        self.kernelSizeSlider.sliderMoved['int'].connect(self.kernelSizeLabel.setNum)
        self.sigmaSizeSlider.sliderMoved['int'].connect(self.sigmaSizeLabel.setNum)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SE-342::Convolution Example"))
        self.groupBox.setTitle(_translate("MainWindow", "預覽"))
        self.groupBox_3.setTitle(_translate("MainWindow", "變數設定"))
        self.label.setText(_translate("MainWindow", "卷積方式"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Roberts 卷積"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Prewitt 卷積"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Sobel 卷積"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Gaussian 濾波"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Mean 濾波"))
        self.comboBox.setItemText(5, _translate("MainWindow", "Median 濾波"))
        self.label_3.setText(_translate("MainWindow", "卷積核大小:"))
        self.kernelSizeLabel.setText(_translate("MainWindow", "3"))
        self.label_2.setText(_translate("MainWindow", "Sigma:"))
        self.sigmaSizeLabel.setText(_translate("MainWindow", "50"))
        self.groupBox_2.setTitle(_translate("MainWindow", "控制鈕"))
        self.pushButton_2.setText(_translate("MainWindow", "應用卷積"))
        self.pushButton.setText(_translate("MainWindow", "應用濾波"))
        self.pushButton_3.setText(_translate("MainWindow", "重置"))
        self.menuMain_Window.setTitle(_translate("MainWindow", "檔案"))
        self.menu.setTitle(_translate("MainWindow", "進階"))
        self.menu_2.setTitle(_translate("MainWindow", "說明"))
        self.menu_3.setTitle(_translate("MainWindow", "顯示"))
        self.actionImportImage.setText(_translate("MainWindow", "匯入圖片檔"))
        self.actionImportImage.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionExportImage.setText(_translate("MainWindow", "匯出圖片檔"))
        self.actionExportImage.setToolTip(_translate("MainWindow", "匯入圖片檔"))
        self.actionExportImage.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionResume.setText(_translate("MainWindow", "恢復默認"))
        self.actionResume.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionZoomIn.setText(_translate("MainWindow", "放大一點"))
        self.actionZoomIn.setToolTip(_translate("MainWindow", "放大一點"))
        self.actionZoomIn.setShortcut(_translate("MainWindow", "Ctrl+="))
        self.actionZoomOut.setText(_translate("MainWindow", "縮小一點"))
        self.actionZoomOut.setToolTip(_translate("MainWindow", "縮小一點"))
        self.actionZoomOut.setShortcut(_translate("MainWindow", "Ctrl+-"))
        self.actionReset.setText(_translate("MainWindow", "實際大小"))
        self.actionReset.setToolTip(_translate("MainWindow", "實際大小"))
        self.actionReset.setShortcut(_translate("MainWindow", "Ctrl+0"))
        self.actionShowAbout.setText(_translate("MainWindow", "App 版本"))
        self.actionShowAbout.setToolTip(_translate("MainWindow", "App 版本"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
